### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by Zendio** [cyberjunky/home-assistant-p2000#12]
Hey there!
With the new update, I'm only getting messages that include the location, which works as intended! Thanks for that!

Somehow I'm still getting every message twice, but I'm not sure what's causing it.
Example: 
**1st message:**
> P 2 INCI-01 Liftopsluiting Burgemeester Brokxlaan Tilburg 209433
> Sat, 21 Mar 2020 **11:35:09 +0100**

&

**2nd message:**
> P 2 INCI-01 Liftopsluiting Burgemeester Brokxlaan Tilburg 209433
> Sat, 21 Mar 2020 **11:46:07 +0100**

There's a difference in the timestamp. When I go to livep2000.nl, I only see one message that corresponds with what HA tells me, which is the first message in the example described above.
The second message isn't showing on livep2000.nl. There is however a new message on the site that reads:

> **11:46:07**21-03-2020AMBUA2 MOERDIJK rit: 24521 eh: 20107
> 1220607 MKA Midden en West Brabant ( Ambulance 20-107 Roosendaal )
> 1220499 MKA Midden en West Brabant ( Monitorcode )

This is the exact same **time** as the 2nd message in the examples from earlier, but a different P2000 alert.

I hope I explained well enough.

Thanks for all your hard work!

**Comment by cyberjunky** [comment]
Do you have more than one P2000 sensor configured?

**Comment by Zendio** [comment]
Yes 2, one for the province of Zeeland and one for Noord-Brabant.

**Comment by ManCaveMedia** [comment]
I have the exact same issue.
But I only have 1 P2000 sensor configured.

Same story for the P2000 live feed: only one entry found. No idea where the other is coming from.
Please let me know if you need more info, so I can provide it.

**Comment by ualex73** [comment]
The following pull request should fix this:
https://github.com/cyberjunky/home-assistant-p2000/pull/14

**Comment by Zendio** [comment]
Is the fix included in 1.0.12? (23 hours ago according to HACS)

Still doesn't seem to line up correctly. 
![Screenshot 2020-05-06 at 08 18 26](https://user-images.githubusercontent.com/5435734/81143655-9eb61c00-8f72-11ea-908a-c7b4d00c2f1e.png)
![Screenshot 2020-05-06 at 08 18 50](https://user-images.githubusercontent.com/5435734/81143660-a249a300-8f72-11ea-8b53-ca5b07a9f75b.png)

**Comment by ualex73** [comment]
No, the 1.0.12 doesn't include the fix. You need to manually install the "sensor.py" from the github repository.

Your output shows the same as i had also, the timestamp of the second (duplicate) P2000 message is of the 08:41:41 P2000 message, which i believe is skipped (most likely lat/lon is missing). The fix will put the correct time in the P2000 event and in HA it shouldn't trigger a change anymore, because the text/information stays exactly the same.

**Comment by Zendio** [comment]
Thanks, I just followed your advice and will report back!

**Comment by ManCaveMedia** [comment]
> The following pull request should fix this: #14

I made the exact same fix a couple of days ago (not knowing this issue was being worked on) and can confirm it works!

**Comment by Zendio** [comment]
Seems to be working correctly now. Will leave this one open till the update is pushed through HACS.

**Comment by cyberjunky** [comment]
I have created Release 1.0.13, it will appear shortly in HACS.
I have some cleaned up code too (pylinted), but first lets have a working version before I mess it all up again ;-)
I think we can also miss some messages when several are received at the same time and device update is only picking up last one. I may have to trigger device update with a bus signal after each update without having to wait for interval.
